name: 'CustomEnvVar'

on:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Friday
  testvar: value-1

jobs:
  mainjob:
    name: 'Print the env vars'
    runs-on: ubuntu-latest

    env:
      Greeting: Hello All
      testvar: value-2

    steps:
    - name: print-values-of-env-vars
      run: |
        echo "${{ env.Greeting }} ${{ env.First_NAME }}. Today is ${{ DAY_OF_WEEK }}!"
        echo "testvar $testvar"
        echo "testvar ${{ env.testvar }}"
      env:
        First_Name: Student
        testvar: value-3

