name: 'custom GITHUB_ENV var Demo'

on: workflow_dispatch

jobs:
  custom_GITHUB_ENV:
    runs-on: ubuntu-latest
    steps:
    - name: Set the value
      id: stepOne
      run: |
        echo "action_state=yellow" >> $GITHUB_ENV

    - name: Use the Value
      id: stepTwo
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'
